### ISSUE TITLE
Nick - 2 User Stories

### ISSUE THREAD

**Issue by bcu8** [bcu8/CS386-C-Code-Formatter#15]

**Comment by nwwiltshire** [comment]
“As a C programming student, I frequently lose points on GUR formatting issues, and would like to be able to scan my code for errors before I submit.”
“As a C programming professor, I spend a lot of time grading my students’ C files on GUR, and would like a tool that can quickly scan code for errors.”

**Comment by nwwiltshire** [comment]
Priority: Hight
Estimated Time: 45 minutes
