### ISSUE TITLE
Ian - 2 User Stories

### ISSUE THREAD

**Issue by bcu8** [bcu8/CS386-C-Code-Formatter#16]

**Comment by ipt6** [comment]
As an amateur programmer, I’d like to be able to select certain GUR requirements to have fixed, so I can work on improving certain aspects of my code.
Priority: 8
Estimated Hours: 2

**Comment by ipt6** [comment]
As a programmer working on a large team, I’d like to be able to automatically format code added to our repository, to be efficient.
Priority: 6
Estimated Hours: 10
